changelog:
  categories:
    - title: 'Contest Updates'
      labels:
        - 'contest'
    - title: 'Problemset Additions'
      labels:
        - 'problemset'
    - title: 'Infrastructure and Tooling'
      labels:
        - 'tooling'
    - title: 'Documentation'
      labels:
        - 'documentation'